// crates/fe_ui_core/src/entity.rs
//
// The Ghost ECS — internal entity store for Ferrum fe_ui.
//
// ─── What this is ────────────────────────────────────────────────────────────
//
//  Ferrum runs three independent subsystems simultaneously:
//    - Taffy   (layout)   — assigns a NodeId to each widget
//    - Rapier  (physics)  — assigns a RigidBodyHandle to each widget
//    - wgpu    (render)   — assigns an instance buffer index to each widget
//
//  Something must own the mapping between all three.
//  That something is the GhostWorld.
//
//  GhostEntity holds the cross-system handles for one widget alongside
//  its configuration (physics props, style, joint type, altitude).
//
// ─── Why "Ghost" ─────────────────────────────────────────────────────────────
//
//  It's an ECS. It just doesn't tell anyone.
//
//  The developer never sees an EntityId. They write `Button { }` and the
//  #[component] macro registers the entity across all three systems invisibly.
//
//  GhostWorld is pub(crate) only. The #[component] macro is the only public
//  door in. If you find yourself needing direct entity access to build
//  something, open an issue — the public API has a gap.
//
// ─── Handles ─────────────────────────────────────────────────────────────────
//
//  Taffy and Rapier use opaque handle types that we can't import here without
//  creating circular dependencies (fe_ui_core must not import fe_ui_taffy or
//  fe_ui_rapier). We store their handles as u64 and cast at the subsystem
//  boundary. Each subsystem crate provides its own EntityRegistry that maps
//  EntityId → its native handle type.
//
//  This is the explicit trade-off for the "no cross-subsystem imports" rule.
//
// ─── Lifecycle ───────────────────────────────────────────────────────────────
//
//  1. #[component] macro calls GhostWorld::spawn(SpawnProps)
//  2. GhostWorld assigns an EntityId, stores the GhostEntity
//  3. fe_ui_taffy::LayoutTree::register(id, style) fills taffy_node
//  4. fe_ui_rapier::PhysicsWorld::spawn_body(id, physics) fills rapier_body
//  5. fe_ui_wgpu::Renderer::reserve_instance(id) fills wgpu_index
//  6. Component renders — user never touches EntityId
//  7. On despawn: GhostWorld::despawn(id) → each subsystem cleans up its handle
//
// ─────────────────────────────────────────────────────────────────────────────

use slotmap::{SlotMap, new_key_type};
use crate::{
    physics::{PhysicsProps, BodyType},
    style::Style,
    types::LayoutRect,
};

// ─── EntityId ────────────────────────────────────────────────────────────────

new_key_type! {
    /// The only shared identity across layout, physics, and rendering.
    ///
    /// Generated by SlotMap — guaranteed unique, never reused for the
    /// lifetime of the GhostWorld even after despawn.
    ///
    /// Never exposed in a public API. If a developer needs to identify
    /// a widget, they use a signal or a callback — not an EntityId.
    pub struct EntityId;
}

// ─── JointType ───────────────────────────────────────────────────────────────

/// The physical joint between a child body and its parent body.
///
/// Default is Fixed (weld) — children move identically with their parent.
/// When a child declares `Physics::dynamic()`, the joint upgrades to Spring,
/// giving the child physical lag and jiggle relative to the parent.
///
/// This is the "Parent-Joint Model" from FE_STD_SPEC.md.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum JointType {
    /// Child is rigidly welded to parent. Moves identically.
    /// This is the default — zero config required.
    #[default]
    Fixed,

    /// Child follows parent via spring force.
    /// Lags behind on fast moves. Bounces on settle. Feels alive.
    /// Activated automatically when child declares Physics::dynamic().
    Spring,

    /// Child is detached. Governed only by its own forces.
    /// Activated when child declares Physics::free().
    Free,
}

impl JointType {
    /// Resolve the joint type a child should have given its physics body type.
    ///
    /// This is the automatic upgrade rule:
    ///   Static or unset   → Fixed  (moves with parent, zero cost)
    ///   Dynamic           → Spring (follows with lag/jiggle)
    ///   Kinematic         → Fixed  (kinematic precision — no jiggle)
    pub fn for_body_type(body_type: BodyType) -> Self {
        match body_type {
            BodyType::Dynamic   => JointType::Spring,
            BodyType::Kinematic => JointType::Fixed,
            BodyType::Static    => JointType::Fixed,
        }
    }
}

// ─── Cross-system handle slots ────────────────────────────────────────────────

/// Status of a subsystem handle.
///
/// Handles are filled in after spawn — the three subsystem crates each
/// register their handle in the frame after the entity is created.
/// None means "not yet registered" rather than "error".
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum HandleSlot {
    /// Not yet registered by the subsystem.
    Pending,
    /// Registered — stores the opaque u64 handle.
    Registered(u64),
}

impl HandleSlot {
    pub fn is_pending(&self) -> bool {
        matches!(self, HandleSlot::Pending)
    }

    pub fn is_registered(&self) -> bool {
        matches!(self, HandleSlot::Registered(_))
    }

    /// Returns the inner handle value, panicking if still pending.
    /// Only call this after the subsystem has registered the entity.
    pub fn unwrap(&self) -> u64 {
        match self {
            HandleSlot::Registered(h) => *h,
            HandleSlot::Pending => panic!(
                "HandleSlot::unwrap() called on a Pending handle. \
                 The subsystem has not registered this entity yet."
            ),
        }
    }

    /// Returns the inner handle value or None if pending.
    pub fn get(&self) -> Option<u64> {
        match self {
            HandleSlot::Registered(h) => Some(*h),
            HandleSlot::Pending       => None,
        }
    }
}

impl Default for HandleSlot {
    fn default() -> Self { HandleSlot::Pending }
}

// ─── GhostEntity ─────────────────────────────────────────────────────────────

/// Internal representation of a single widget entity.
///
/// Holds the cross-system handles and the widget's full configuration.
/// This struct is the source of truth for what a widget IS and HOW it behaves.
///
/// Never accessed directly by user code — always through GhostWorld.
#[derive(Debug)]
pub struct GhostEntity {
    /// Unique identity shared across all three subsystems.
    pub id: EntityId,

    /// Taffy NodeId stored as u64.
    /// Filled by fe_ui_taffy::LayoutTree::register().
    pub taffy_node: HandleSlot,

    /// Rapier RigidBodyHandle stored as u64.
    /// Filled by fe_ui_rapier::PhysicsWorld::spawn_body().
    pub rapier_body: HandleSlot,

    /// Index into fe_ui_wgpu's SDF instance buffer.
    /// Filled by fe_ui_wgpu::Renderer::reserve_instance().
    pub wgpu_index: HandleSlot,

    /// Physics configuration — mass, restitution, stiffness, etc.
    pub physics: PhysicsProps,

    /// Layout style — flex/grid properties, size, padding, etc.
    pub style: Style,

    /// The last Taffy-resolved layout rect.
    /// Updated at the Sync Point. Used as the spring target by Rapier.
    pub layout_rect: LayoutRect,

    /// IDs of all direct children.
    pub children: Vec<EntityId>,

    /// Parent entity ID, if any.
    pub parent: Option<EntityId>,

    /// The joint connecting this entity to its parent.
    /// Resolved automatically from physics.body_type by SpawnProps.
    pub joint: JointType,

    /// Visual altitude above the ground plane (0.0 = flat, higher = floating).
    /// Drives shadow size/blur in the SDF shader. Also sets Z-depth.
    pub altitude: f32,

    /// Whether this entity is currently active in the physics step.
    pub physics_active: bool,
}

impl GhostEntity {
    /// Returns true if all three subsystem handles are registered.
    /// A fully registered entity is ready to be laid out, simulated, and drawn.
    pub fn is_fully_registered(&self) -> bool {
        self.taffy_node.is_registered()
            && self.rapier_body.is_registered()
            && self.wgpu_index.is_registered()
    }
}

// ─── SpawnProps ───────────────────────────────────────────────────────────────

/// Properties provided to GhostWorld::spawn().
/// Built by the #[component] macro from the developer's render! block.
///
/// The developer never constructs this directly — it is the macro's job.
///
/// # Example (what the macro builds from the developer's code)
/// ```rust, ignore
/// // Developer writes:
/// Button {
///     physics: Physics::dynamic().mass(2.0).restitution(0.8),
///     style: style! { width: 200.px, height: 60.px },
/// }
///
/// // Macro builds:
/// SpawnProps {
///     physics:  PhysicsProps { body_type: Dynamic, mass: 2.0, restitution: 0.8, .. },
///     style:    Style { width: Dimension::Px(200.0), height: Dimension::Px(60.0), .. },
///     parent:   Some(parent_entity_id),
///     altitude: 0.0,
/// }
/// ```
#[derive(Debug, Clone)]
pub struct SpawnProps {
    /// Physics configuration for this entity.
    pub physics: PhysicsProps,

    /// Layout style for this entity.
    pub style: Style,

    /// Parent entity ID. None for root entities.
    pub parent: Option<EntityId>,

    /// Visual altitude. Drives shadow and Z-depth.
    pub altitude: f32,
}

impl SpawnProps {
    /// Construct with defaults. Useful for tests and simple components.
    pub fn default_with_parent(parent: Option<EntityId>) -> Self {
        Self {
            physics:  PhysicsProps::default(),
            style:    Style::default(),
            parent,
            altitude: 0.0,
        }
    }
}

impl Default for SpawnProps {
    fn default() -> Self {
        Self {
            physics:  PhysicsProps::default(),
            style:    Style::default(),
            parent:   None,
            altitude: 0.0,
        }
    }
}

// ─── GhostWorld ──────────────────────────────────────────────────────────────

/// The Ghost ECS — internal entity store.
///
/// pub(crate) only. The #[component] macro is the only public door in.
///
/// Responsibilities:
///   - Spawn entities, assign EntityIds, store GhostEntitys
///   - Wire parent-child relationships
///   - Resolve JointType from physics body type
///   - Provide iteration over active entities for the frame loop
///
/// Does NOT:
///   - Know about Taffy, Rapier, or wgpu directly
///   - Own subsystem-specific handles (those are HandleSlots filled externally)
///   - Run layout, physics, or rendering
pub struct GhostWorld {
    entities: SlotMap<EntityId, GhostEntity>,
}

impl GhostWorld {
    pub fn new() -> Self {
        Self {
            entities: SlotMap::with_key(),
        }
    }

    // ── Spawn / despawn ───────────────────────────────────────────────────────

    /// Spawn a new entity from SpawnProps.
    ///
    /// Assigns a unique EntityId. Wires parent-child relationship.
    /// Resolves JointType from physics.body_type.
    /// All subsystem handles start as HandleSlot::Pending.
    ///
    /// Returns the new EntityId.
    pub fn spawn(&mut self, props: SpawnProps) -> EntityId {
        // Resolve joint type from the physics body type.
        // Dynamic body → spring joint (lags/jiggles behind parent).
        // Kinematic or Static → fixed joint (moves with parent exactly).
        let joint = JointType::for_body_type(props.physics.body_type);

        // Altitude from props, merged with physics.altitude if set.
        let altitude = if props.altitude > 0.0 {
            props.altitude
        } else {
            props.physics.altitude
        };

        // Insert the entity. SlotMap generates the EntityId.
        let parent = props.parent;
        let id = self.entities.insert_with_key(|id| GhostEntity {
            id,
            taffy_node:    HandleSlot::Pending,
            rapier_body:   HandleSlot::Pending,
            wgpu_index:    HandleSlot::Pending,
            physics:       props.physics,
            style:         props.style,
            layout_rect:   LayoutRect::default(),
            children:      Vec::new(),
            parent,
            joint,
            altitude,
            physics_active: false,
        });

        // Wire the parent → child relationship.
        if let Some(parent_id) = parent {
            if let Some(parent_entity) = self.entities.get_mut(parent_id) {
                parent_entity.children.push(id);
            }
            // If the parent doesn't exist, we silently skip — the entity
            // is still valid, just unparented. This can happen during hot
            // reload when parent/child spawn order is non-deterministic.
        }

        id
    }

    /// Despawn an entity and remove it from its parent's child list.
    ///
    /// Children of the despawned entity are NOT automatically despawned —
    /// the caller (the frame loop) is responsible for despawning the subtree
    /// in the correct order (leaves first).
    ///
    /// Returns the removed GhostEntity so the caller can clean up subsystem
    /// handles (Taffy node, Rapier body, wgpu instance).
    pub fn despawn(&mut self, id: EntityId) -> Option<GhostEntity> {
        let entity = self.entities.remove(id)?;

        // Remove from parent's child list.
        if let Some(parent_id) = entity.parent {
            if let Some(parent_entity) = self.entities.get_mut(parent_id) {
                parent_entity.children.retain(|&child_id| child_id != id);
            }
        }

        Some(entity)
    }

    // ── Handle registration ───────────────────────────────────────────────────

    /// Called by fe_ui_taffy after creating the Taffy node for this entity.
    pub fn register_taffy_node(&mut self, id: EntityId, handle: u64) {
        if let Some(entity) = self.entities.get_mut(id) {
            entity.taffy_node = HandleSlot::Registered(handle);
        }
    }

    /// Called by fe_ui_rapier after spawning the Rapier body for this entity.
    pub fn register_rapier_body(&mut self, id: EntityId, handle: u64) {
        if let Some(entity) = self.entities.get_mut(id) {
            entity.rapier_body = HandleSlot::Registered(handle);
            entity.physics_active = true;
        }
    }

    /// Called by fe_ui_wgpu after reserving the instance buffer slot.
    pub fn register_wgpu_index(&mut self, id: EntityId, index: u32) {
        if let Some(entity) = self.entities.get_mut(id) {
            entity.wgpu_index = HandleSlot::Registered(index as u64);
        }
    }

    // ── Layout rect update ────────────────────────────────────────────────────

    /// Update the cached layout rect for an entity.
    /// Called by the frame loop after Taffy resolves target positions.
    pub fn update_layout_rect(&mut self, id: EntityId, rect: LayoutRect) {
        if let Some(entity) = self.entities.get_mut(id) {
            entity.layout_rect = rect;
        }
    }

    // ── Reads ─────────────────────────────────────────────────────────────────

    pub fn get(&self, id: EntityId) -> Option<&GhostEntity> {
        self.entities.get(id)
    }

    pub fn get_mut(&mut self, id: EntityId) -> Option<&mut GhostEntity> {
        self.entities.get_mut(id)
    }

    pub fn contains(&self, id: EntityId) -> bool {
        self.entities.contains_key(id)
    }

    /// Iterate over all entities. Order is not guaranteed.
    pub fn iter(&self) -> impl Iterator<Item = &GhostEntity> {
        self.entities.values()
    }

    pub fn iter_mut(&mut self) -> impl Iterator<Item = &mut GhostEntity> {
        self.entities.values_mut()
    }

    /// Iterate over all entities that are fully registered across all three
    /// subsystems and ready to be included in the frame loop.
    pub fn iter_ready(&self) -> impl Iterator<Item = &GhostEntity> {
        self.entities.values().filter(|e| e.is_fully_registered())
    }

    /// Iterate over entities that still have pending subsystem handles.
    /// These need to be registered before they appear in the render.
    pub fn iter_pending(&self) -> impl Iterator<Item = &GhostEntity> {
        self.entities.values().filter(|e| !e.is_fully_registered())
    }

    /// Returns all direct children of an entity, in spawn order.
    pub fn children_of(&self, id: EntityId) -> Vec<EntityId> {
        self.entities
            .get(id)
            .map(|e| e.children.clone())
            .unwrap_or_default()
    }

    /// Walk the subtree rooted at `id` in depth-first order.
    /// Useful for despawning a subtree (process leaves first by reversing).
    pub fn subtree_ids(&self, id: EntityId) -> Vec<EntityId> {
        let mut result = Vec::new();
        self.collect_subtree(id, &mut result);
        result
    }

    fn collect_subtree(&self, id: EntityId, out: &mut Vec<EntityId>) {
        out.push(id);
        if let Some(entity) = self.entities.get(id) {
            for &child_id in &entity.children {
                self.collect_subtree(child_id, out);
            }
        }
    }

    // ── Stats ─────────────────────────────────────────────────────────────────

    pub fn entity_count(&self) -> usize {
        self.entities.len()
    }

    pub fn pending_count(&self) -> usize {
        self.entities.values().filter(|e| !e.is_fully_registered()).count()
    }

    pub fn ready_count(&self) -> usize {
        self.entities.values().filter(|e| e.is_fully_registered()).count()
    }
}

impl Default for GhostWorld {
    fn default() -> Self { Self::new() }
}

impl std::fmt::Debug for GhostWorld {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("GhostWorld")
            .field("entities", &self.entities.len())
            .field("pending",  &self.pending_count())
            .field("ready",    &self.ready_count())
            .finish()
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::physics::{BodyType, PhysicsProps};

    fn default_props() -> SpawnProps {
        SpawnProps::default()
    }

    fn props_with_body_type(body_type: BodyType) -> SpawnProps {
        SpawnProps {
            physics: PhysicsProps {
                body_type,
                ..PhysicsProps::default()
            },
            ..SpawnProps::default()
        }
    }

    // ── Spawn ─────────────────────────────────────────────────────────────────

    #[test]
    fn spawn_returns_valid_id() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        assert!(world.contains(id));
    }

    #[test]
    fn spawn_returns_unique_ids() {
        let mut world = GhostWorld::new();
        let a = world.spawn(default_props());
        let b = world.spawn(default_props());
        let c = world.spawn(default_props());
        assert_ne!(a, b);
        assert_ne!(b, c);
        assert_ne!(a, c);
    }

    #[test]
    fn spawn_increments_entity_count() {
        let mut world = GhostWorld::new();
        assert_eq!(world.entity_count(), 0);
        world.spawn(default_props());
        assert_eq!(world.entity_count(), 1);
        world.spawn(default_props());
        assert_eq!(world.entity_count(), 2);
    }

    #[test]
    fn spawn_handles_start_pending() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        let e = world.get(id).unwrap();
        assert!(e.taffy_node.is_pending());
        assert!(e.rapier_body.is_pending());
        assert!(e.wgpu_index.is_pending());
    }

    #[test]
    fn spawn_entity_not_fully_registered_until_all_handles_set() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        assert!(!world.get(id).unwrap().is_fully_registered());
    }

    #[test]
    fn spawn_stores_style() {
        use crate::style::{Style, Dimension};
        let mut world = GhostWorld::new();
        let mut style = Style::default();
        style.width = Dimension::Px(200.0);
        let props = SpawnProps { style: style.clone(), ..default_props() };
        let id = world.spawn(props);
        assert!(matches!(world.get(id).unwrap().style.width, Dimension::Px(w) if (w - 200.0).abs() < 1e-6));
    }

    #[test]
    fn spawn_stores_altitude() {
        let mut world = GhostWorld::new();
        let props = SpawnProps { altitude: 4.0, ..default_props() };
        let id = world.spawn(props);
        assert!((world.get(id).unwrap().altitude - 4.0).abs() < 1e-6);
    }

    #[test]
    fn spawn_no_parent_has_none_parent() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        assert!(world.get(id).unwrap().parent.is_none());
    }

    // ── JointType resolution ─────────────────────────────────────────────────

    #[test]
    fn joint_type_static_body_is_fixed() {
        let mut world = GhostWorld::new();
        let id = world.spawn(props_with_body_type(BodyType::Static));
        assert_eq!(world.get(id).unwrap().joint, JointType::Fixed);
    }

    #[test]
    fn joint_type_kinematic_body_is_fixed() {
        let mut world = GhostWorld::new();
        let id = world.spawn(props_with_body_type(BodyType::Kinematic));
        assert_eq!(world.get(id).unwrap().joint, JointType::Fixed);
    }

    #[test]
    fn joint_type_dynamic_body_is_spring() {
        let mut world = GhostWorld::new();
        let id = world.spawn(props_with_body_type(BodyType::Dynamic));
        assert_eq!(world.get(id).unwrap().joint, JointType::Spring);
    }

    // ── Parent-child relationships ────────────────────────────────────────────

    #[test]
    fn spawn_with_parent_sets_parent_field() {
        let mut world = GhostWorld::new();
        let parent_id = world.spawn(default_props());
        let child_props = SpawnProps {
            parent: Some(parent_id),
            ..default_props()
        };
        let child_id = world.spawn(child_props);
        assert_eq!(world.get(child_id).unwrap().parent, Some(parent_id));
    }

    #[test]
    fn spawn_with_parent_adds_to_parent_children() {
        let mut world = GhostWorld::new();
        let parent_id = world.spawn(default_props());
        let child_props = SpawnProps { parent: Some(parent_id), ..default_props() };
        let child_id = world.spawn(child_props);
        assert!(world.get(parent_id).unwrap().children.contains(&child_id));
    }

    #[test]
    fn spawn_multiple_children_all_in_parent_list() {
        let mut world = GhostWorld::new();
        let parent_id = world.spawn(default_props());

        let c1 = world.spawn(SpawnProps { parent: Some(parent_id), ..default_props() });
        let c2 = world.spawn(SpawnProps { parent: Some(parent_id), ..default_props() });
        let c3 = world.spawn(SpawnProps { parent: Some(parent_id), ..default_props() });

        let children = &world.get(parent_id).unwrap().children;
        assert!(children.contains(&c1));
        assert!(children.contains(&c2));
        assert!(children.contains(&c3));
        assert_eq!(children.len(), 3);
    }

    #[test]
    fn children_of_returns_correct_ids() {
        let mut world = GhostWorld::new();
        let parent_id = world.spawn(default_props());
        let c1 = world.spawn(SpawnProps { parent: Some(parent_id), ..default_props() });
        let c2 = world.spawn(SpawnProps { parent: Some(parent_id), ..default_props() });

        let children = world.children_of(parent_id);
        assert!(children.contains(&c1));
        assert!(children.contains(&c2));
    }

    #[test]
    fn children_of_nonexistent_returns_empty() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        let removed = world.despawn(id).unwrap();
        let _ = removed;
        let children = world.children_of(id);
        assert!(children.is_empty());
    }

    // ── Despawn ───────────────────────────────────────────────────────────────

    #[test]
    fn despawn_removes_entity() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        assert!(world.contains(id));
        world.despawn(id);
        assert!(!world.contains(id));
    }

    #[test]
    fn despawn_returns_entity() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        let entity = world.despawn(id);
        assert!(entity.is_some());
        assert_eq!(entity.unwrap().id, id);
    }

    #[test]
    fn despawn_nonexistent_returns_none() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        world.despawn(id);
        // Despawning again returns None
        assert!(world.despawn(id).is_none());
    }

    #[test]
    fn despawn_removes_from_parent_children() {
        let mut world = GhostWorld::new();
        let parent_id = world.spawn(default_props());
        let child_id  = world.spawn(SpawnProps {
            parent: Some(parent_id),
            ..default_props()
        });

        assert!(world.get(parent_id).unwrap().children.contains(&child_id));
        world.despawn(child_id);
        assert!(!world.get(parent_id).unwrap().children.contains(&child_id));
    }

    #[test]
    fn despawn_decrements_entity_count() {
        let mut world = GhostWorld::new();
        let a = world.spawn(default_props());
        let b = world.spawn(default_props());
        assert_eq!(world.entity_count(), 2);
        world.despawn(a);
        assert_eq!(world.entity_count(), 1);
        world.despawn(b);
        assert_eq!(world.entity_count(), 0);
    }

    // ── Handle registration ───────────────────────────────────────────────────

    #[test]
    fn register_taffy_node_sets_handle() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        world.register_taffy_node(id, 42);
        assert_eq!(world.get(id).unwrap().taffy_node, HandleSlot::Registered(42));
    }

    #[test]
    fn register_rapier_body_sets_handle_and_activates() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        assert!(!world.get(id).unwrap().physics_active);
        world.register_rapier_body(id, 99);
        assert_eq!(world.get(id).unwrap().rapier_body, HandleSlot::Registered(99));
        assert!(world.get(id).unwrap().physics_active);
    }

    #[test]
    fn register_wgpu_index_sets_handle() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        world.register_wgpu_index(id, 7);
        assert_eq!(world.get(id).unwrap().wgpu_index, HandleSlot::Registered(7));
    }

    #[test]
    fn fully_registered_after_all_three_handles() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());

        assert!(!world.get(id).unwrap().is_fully_registered());

        world.register_taffy_node(id,  1);
        assert!(!world.get(id).unwrap().is_fully_registered());

        world.register_rapier_body(id, 2);
        assert!(!world.get(id).unwrap().is_fully_registered());

        world.register_wgpu_index(id,  3);
        assert!(world.get(id).unwrap().is_fully_registered());
    }

    // ── iter_ready / iter_pending ─────────────────────────────────────────────

    #[test]
    fn iter_pending_includes_unregistered() {
        let mut world = GhostWorld::new();
        world.spawn(default_props());
        world.spawn(default_props());

        let pending: Vec<_> = world.iter_pending().collect();
        assert_eq!(pending.len(), 2);
    }

    #[test]
    fn iter_ready_excludes_unregistered() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        world.spawn(default_props()); // stays pending

        world.register_taffy_node(id,  1);
        world.register_rapier_body(id, 2);
        world.register_wgpu_index(id,  3);

        let ready: Vec<_> = world.iter_ready().collect();
        assert_eq!(ready.len(), 1);
        assert_eq!(ready[0].id, id);
    }

    // ── Subtree ───────────────────────────────────────────────────────────────

    #[test]
    fn subtree_ids_single_entity() {
        let mut world = GhostWorld::new();
        let id = world.spawn(default_props());
        let subtree = world.subtree_ids(id);
        assert_eq!(subtree, vec![id]);
    }

    #[test]
    fn subtree_ids_with_children() {
        let mut world = GhostWorld::new();
        let root = world.spawn(default_props());
        let c1   = world.spawn(SpawnProps { parent: Some(root), ..default_props() });
        let c2   = world.spawn(SpawnProps { parent: Some(root), ..default_props() });
        let gc1  = world.spawn(SpawnProps { parent: Some(c1),   ..default_props() });

        let subtree = world.subtree_ids(root);
        assert!(subtree.contains(&root));
        assert!(subtree.contains(&c1));
        assert!(subtree.contains(&c2));
        assert!(subtree.contains(&gc1));
        assert_eq!(subtree.len(), 4);
    }

    #[test]
    fn subtree_ids_root_is_first() {
        let mut world = GhostWorld::new();
        let root = world.spawn(default_props());
        let _c1  = world.spawn(SpawnProps { parent: Some(root), ..default_props() });

        let subtree = world.subtree_ids(root);
        assert_eq!(subtree[0], root);
    }

    // ── Layout rect ──────────────────────────────────────────────────────────

    #[test]
    fn update_layout_rect_stores_value() {
        use crate::types::LayoutRect;
        let mut world = GhostWorld::new();
        let id   = world.spawn(default_props());
        let rect = LayoutRect::new(10.0, 20.0, 100.0, 50.0);
        world.update_layout_rect(id, rect);
        assert_eq!(world.get(id).unwrap().layout_rect, rect);
    }

    // ── HandleSlot ───────────────────────────────────────────────────────────

    #[test]
    fn handle_slot_pending_is_pending() {
        assert!(HandleSlot::Pending.is_pending());
        assert!(!HandleSlot::Pending.is_registered());
    }

    #[test]
    fn handle_slot_registered_is_registered() {
        assert!(HandleSlot::Registered(42).is_registered());
        assert!(!HandleSlot::Registered(42).is_pending());
    }

    #[test]
    fn handle_slot_get_pending_is_none() {
        assert_eq!(HandleSlot::Pending.get(), None);
    }

    #[test]
    fn handle_slot_get_registered_is_some() {
        assert_eq!(HandleSlot::Registered(7).get(), Some(7));
    }

    #[test]
    fn handle_slot_unwrap_registered() {
        assert_eq!(HandleSlot::Registered(99).unwrap(), 99);
    }

    #[test]
    #[should_panic(expected = "Pending handle")]
    fn handle_slot_unwrap_pending_panics() {
        HandleSlot::Pending.unwrap();
    }

    // ── JointType::for_body_type ──────────────────────────────────────────────

    #[test]
    fn joint_for_body_type_static_is_fixed() {
        assert_eq!(JointType::for_body_type(BodyType::Static),    JointType::Fixed);
    }

    #[test]
    fn joint_for_body_type_kinematic_is_fixed() {
        assert_eq!(JointType::for_body_type(BodyType::Kinematic), JointType::Fixed);
    }

    #[test]
    fn joint_for_body_type_dynamic_is_spring() {
        assert_eq!(JointType::for_body_type(BodyType::Dynamic),   JointType::Spring);
    }

    // ── Stats ─────────────────────────────────────────────────────────────────

    #[test]
    fn stats_pending_and_ready_counts() {
        let mut world = GhostWorld::new();

        let a = world.spawn(default_props());
        let _b = world.spawn(default_props());

        assert_eq!(world.pending_count(), 2);
        assert_eq!(world.ready_count(),   0);

        world.register_taffy_node(a,  1);
        world.register_rapier_body(a, 2);
        world.register_wgpu_index(a,  3);

        assert_eq!(world.pending_count(), 1);
        assert_eq!(world.ready_count(),   1);
    }
}
